### ISSUE TITLE
Unexpected exception while grade saving

### ISSUE THREAD

**Issue by Smurtta** [changeweb/Unifiedtransform#100] opened 2019-04-14 18:21 UTC
I tried to save a grade and received this exception
![изображение](https://user-images.githubusercontent.com/49613570/56097276-c9ae7780-5efa-11e9-98e2-367becf4f781.png)
![изображение](https://user-images.githubusercontent.com/49613570/56097292-ed71bd80-5efa-11e9-97f9-1a063aed408d.png)

**Comment by changeweb** [comment] 2019-04-14 18:50
@Smurtta I've fixed this issue and going to upload the patch in few minutes. Let me know if this solves your issue.

**Comment by changeweb** [comment] 2019-04-14 18:56
@Smurtta PR merged. Update your repository.

**Comment by Smurtta** [comment] 2019-04-15 06:57
Nope
![image](https://user-images.githubusercontent.com/49613570/56112853-e7182b80-5f64-11e9-976a-4c59a3a33e7b.png)

**Comment by changeweb** [comment] 2019-04-15 07:46
@Smurtta We both are right. The problem is you have installed [Laravel BATCH (BULK) latest](https://github.com/mavinoo/laravelBatch) using composer and mine was [Laravel BATCH (BULK) v2.0](https://github.com/mavinoo/laravelBatch/tree/v2.0).

In Latest version

   Batch::update(new Grade, $value, $index);

works.
where in v2.0

    Batch::update('grades', $value, $index);

works.

Good catch. I should specify the version in composer.json

**Comment by changeweb** [comment] 2019-04-15 08:15
@Smurtta  I've merged a PR using Laravel BATCH (BULK) v2.0 as working. Update your repository with latest master branch and run `composer update` and then `composer dump-autoload`.

**Closed** 2019-04-15 09:33 UTC
Labels: Bug Fixed :heavy_check_mark:
